// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // API キーはリポジトリに含めず、--dart-define で注入する。
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:174669528481:android:46086feb0a8db9e18f9fe0',
    messagingSenderId: '174669528481',
    projectId: 'aruku-app',
    storageBucket: 'aruku-app.firebasestorage.app',
  );

  // appId は android / ios と違いコードに焼いていない。Firebase Console への Web
  // アプリ登録で初めて確定するため、値を持たないまま偽の定数を置くより
  // dart-define へ寄せて注入漏れを起動時に落とす（main.dart の
  // _assertFirebaseOptionsComplete）。#359 参照。
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID'),
    messagingSenderId: '174669528481',
    projectId: 'aruku-app',
    authDomain: 'aruku-app.firebaseapp.com',
    storageBucket: 'aruku-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // API キーはリポジトリに含めず、--dart-define で注入する。
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:174669528481:ios:98b31bea7d420d858f9fe0',
    messagingSenderId: '174669528481',
    projectId: 'aruku-app',
    storageBucket: 'aruku-app.firebasestorage.app',
    iosBundleId: 'com.aruku.aruku',
  );
}
